sudo: false

language: erlang

otp_release:
  - 17.4
  - 17.3
  - 17.1
  - 17.0

before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.3.zip
  - unzip -d elixir v1.0.3.zip

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get

script: mix test

after_script:
  - MIX_ENV=docs mix inch.report

after_success:
  - mix compile
  - mix coveralls.travis
